stages:
  - lint
  - test

image: python:3.12-slim

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest-cov

.rules: &rules
  - if: $CI_PIPELINE_SOURCE == "push"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"

lint:
  stage: lint
  script:
    - isort --check-only .
    - black --check .
    - flake8 .
    - mypy .
  rules: *rules

tests:
  stage: test
  script:
    - pytest --cov=app --cov-report=xml:coverage.xml
  rules: *rules